Detached scrcpy process

diff --git a/wireless-scrcpy b/wireless-scrcpy
--- a/wireless-scrcpy
+++ b/wireless-scrcpy
@@ -15,9 +15,19 @@ reset="\e[0m"
 
 # Argument Parsing
 secure="FOR SECURITY REASON, DON'T USE THIS SCRIPT ON PUBLIC WIFI unless you know what you're doing!!"
-fail="FAILED TO CONNECT! Your laptop and your phone are not in the same discoverable network"
+fail="FAILED TO CONNECT!\nYour laptop and your phone are not in the same discoverable network"
 usbfail="FAILED TO CONNECT! Plug in your phone"
 scrcpyfail="FAIL! You don't unplug your phone"
+
+help() {
+     echo -e "${bold}SCRCPY WIRELESS CONNECTION SCRIPT${reset}"
+     echo -e "Semi-automated, make your work easier\n"
+     echo -e "${bold}USAGE:\t\t\t${green}${bold}wireless-scrcpy <OPTIONS>${reset}"
+     echo -e "\n${bold}OPTIONS:${reset}"
+     echo -e "{no option}\t\tConnect and open scrcpy"
+     echo -e "-q or --quiet\t\tConnect ADB TCPIP and open SCRCPY later"
+     echo -e "-h or --help\t\tTo display this help"
+}
 
 ip() {
      adb shell ip route | awk '{print $9}' | sed -n '2p' | xargs -I{} adb connect {}:5555
@@ -40,6 +50,18 @@ port() {
 case $1 in
      -q|--quiet)
           quiet=true
+          ;;
+     -h|--help)
+          help && exit
+          ;;
+     -*)
+          echo -e "${red}${bold}WRONG OPTION FLAG!${reset}"
+          echo -e "${green}${bold}wireless-scrcpy <OPTIONS>${reset}"
+          echo -e "${bold}\nOPTIONS:${reset}"
+          echo -e "{no option}\t\tJust connect right away"
+          echo -e "-h or --help\t\tTo display help"
+          echo -e "-q or --quiet\t\tConnect ADB TCPIP and open SCRCPY later"
+          exit
           ;;
      *)
           quiet=false
@@ -75,7 +97,7 @@ if [ $quiet = "false" ]
      then
           whiptail --msgbox "Unplug your Android Phone, Press ENTER to continue!" 10 40
           echo -e "${bold}Opening scrcpy..${reset}"
-          scrcpy -b2M -m800 >/dev/null 2>&1 || echo -e "${red}${bold}${scrcpyfail}${reset}"
+          $(scrcpy -b2M -m800 </dev/null &>/dev/null & ) || echo -e "${red}${bold}${scrcpyfail}${reset}"
      else
           echo -e "${bold}Unplug your phone, and you can open scrcpy anytime..${reset}"
 fi
